source 'https://github.com/CocoaPods/Specs.git'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

target 'example' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # target 'exampleTests' do
  #   inherit! :complete
  #   # Pods for testing
  # end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
# #platform :ios, '9.0'
# require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# target 'example' do
#   # React-Native Pods for example
#   pod 'React', :path => '../node_modules/react-native/'
#   pod 'React-Core', :path => '../node_modules/react-native/React'
#   pod 'React-DevSupport', :path => '../node_modules/react-native/React'
#   # pod 'React-fishhook', :path => '../node_modules/react-native/Libraries/fishhook'
#   pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
#   pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
#   pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
#   pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
#   pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
#   pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
#   pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
#   pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
#   pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
#   pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'

#   pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
#   pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
#   pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
#   pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
#   pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

#   pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
#   pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
#   pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

#   use_native_modules!


# end
